version: '3'
services:
    checkin:
        user: "1000:1000"
        build: .
        volumes:
            - ../checkin-data:/data
        environment:
            DISCORD_BOT_LOGFILE: /data/discord.log
